services:
  - type: web
    name: furniture-store-django
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn furniture_store.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true

      - key: DEBUG
        value: False

      - key: PYTHON_VERSION
        value: 3.12.3